spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql : true
        use_sql_comments : true
  datasource:
    url: jdbc:h2:file:~/social-multiplication;DB_CLOSE_ON_EXIT=FALSE;