
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false

server:
  port: 8761
