server:
  port: 8000

zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    multiplications:
      path: /multiplication/**
      service-id: multiplication
      strip-prefix: false

    results:
      path: /results/**
      service-id: multiplication
      strip-prefix: false

    leaders:
      path: /leaders/**
      service-id: gamification
      strip-prefix: false

    stats:
      path: /stats/**
      service-id: gamification
      strip-prefix: false

management:
  endpoint:
    routes:
      sensitive: false
    httptrace:
      sensitive: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
